###
Get http://localhost:3001/posts
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RlZDI2OWUwNzU0NTY1ZDkwNTA2NDciLCJpYXQiOjE3NDI2NTYxMTMsImV4cCI6MTc0MjkxNTMxM30.K23xtlPAol8Ahbyq1qC9ceJmNzHwaPjIDA11AIrOrRs
###

POST http://localhost:3000/posts
Content-Type: application/json
authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RkZTdiNTI0NWJjY2Q3NWIzMGQ3MTAiLCJpYXQiOjE3NDI1OTYwMjMsImV4cCI6MTc0Mjg1NTIyM30.YptISZuYPXwESWcFtCAGTclC_AqXM9gaq6o0l5MrwOk

{
   "title": "Updated Title",
    "content": "This is the updated content of the post.",
    "owner": "5f7d1b3b9af79facedf463e9"
}

###
GET http://localhost:3000/comments/?postId=67d9ca8ba6b0d96f229b36c0




###
POST http://localhost:3001/auth/register
Content-Type: application/json

{
    "username": "admin",
    "email": "admin@a.com",
    "password": "admin"
} 


###
POST http://localhost:3001/auth/login
Content-Type: application/json

{
    "username": "bar",
    "password": "bar"
}


###
POST http://localhost:3000/auth/refresh
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RkZWMwNTNiMWFlZDE4MmUxZTgwMDEiLCJpYXQiOjE3NDI1OTcxMjcsImV4cCI6MTc0Mjg1NjMyN30.DaYdBcsERGMx9ZaNvTb89aLGVI0m2X9umMKrVrqLBRo"
}



###
POST http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RkZWMwNTNiMWFlZDE4MmUxZTgwMDEiLCJyYW5kb20iOiIwLjQ3NzI0NDQzNzk0NzYyNzk0IiwiaWF0IjoxNzQyNTk3Mjc0LCJleHAiOjE3NDMyMDIwNzR9.jN6sZj6ZYXlTGkuSQ8ZAHq__1T11Cj13DOzmxVPCMes"
}


###
GET http://localhost:3001/usres/me
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJfaWQiOiI2N2RkZWMwNTNiMWFlZDE4MmUxZTgwMDEiLCJyYW5kb20iOiIwLjQ3NzI0NDQzNzk0NzYyNzk0IiwiaWF0IjoxNzQyNTk3Mjc0LCJleHAiOjE3NDMyMDIwNzR9.jN6sZj6ZYXlTGkuSQ8ZAHq__1T11Cj13DOzmxVPCMes"
}


###
Get http://localhost:3001/users
content-type: application/json



###
POST http://localhost:3001/files